language: python
python:
 - "2.7"
before_script:
 - sleep 15
services:
  - rabbitmq
  - mongodb
#command to install deps:
install: "pip install -r testing_requirements.txt && pip install -r requirements.txt"
#command to run tests:
script: 
 - find . -name "*.py" -exec pep8 {} \;
 - nosetests --with-coverage --cover-package=config_manager,stores,workers,queue_manager
