language: python
python:
 - "2.7"
before_script:
 - sleep 15
services:
  - rabbitmq
  - mongodb
install:
 - "pip install -r testing_requirements.txt && pip install -r requirements.txt"
 - "pip install --upgrade git+https://github.com/BeneDicere/metahosting-common"
script:
 - find . -name "*.py" -exec pep8 {} \;
 - nosetests --with-coverage --cover-package=config_manager,stores,workers,queue_managers,urlbuilders
 - radon mi config_manager stores workers queue_managers urlbuilders
 - radon cc config_manager stores workers queue_managers urlbuilders
