language: python
python:
 - "2.7"
services:
  - rabbitmq
#command to install deps:
install: "pip install -r testing_requirements.txt"
#command to run tests:
script: 
 - find . -name "*.py" -exec pep8 {} \;
 - nosetests --with-coverage --cover-package=facade,stores,queue_managers,autho
